# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9144f6f472bdbd37db7358a169986db2c503f3c055ba03c289c7343f44b3a7c26ec982cb22a73f98c3498f81059749a94adee7b75482eb403d07c75e33e41ba6

test:
  secret_key_base: 332783c98141e071f79108278c493e86e9ba38708fcc55b6561fd3aa9020223926e676b859a01e709dd2103fdda20c2006065649dabe40a54fa5a96a7d113028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
